### ISSUE TITLE
px-vis-gridlines dark theme styling

### ISSUE THREAD

**Issue by andrealperry** [vaadin/px-vis-boxplot#53] opened 2018-02-08 19:20 UTC
Current state:
<img width="530" alt="screen shot 2018-02-08 at 11 03 28 am" src="https://user-images.githubusercontent.com/30873778/35993358-efb7be96-0cc1-11e8-8920-5e1c2324c6c0.png">

Expected state, px-vis-gridlines = $gray15
<img width="1328" alt="screen shot 2018-02-08 at 11 03 55 am" src="https://user-images.githubusercontent.com/30873778/35993375-018d9cd0-0cc2-11e8-9977-1b41a57cabf7.png">

**Comment by drewharvey** [comment] 2018-02-08 21:15
The css vars are being updated correctly.  The issue is that the gridlines component is not seeing the css var changes (it is not updating its styling and/or redrawing).  Should the px-vis-gridlines component listen for css changes and update automatically?  Or is it the parent components responsibility to tell the gridlines?

**Comment by nonmetalhail** [comment] 2018-02-12 17:54
This is a known issue with gridlines. It can be closed

**Comment by alump** [comment] 2018-02-12 18:24
Closing issue as asked.

**Closed by alump** 2018-02-12 18:24 UTC
